### ISSUE TITLE
Support more languages

### ISSUE THREAD

**Issue by HiromuHota** [HazyResearch/fonduer#104]
**Is your feature request related to a problem? Please describe.**
My documents are written in Japanese, which is not supported by SpaCy hence not by Fonduer.

**Describe the solution you'd like**
According to [SpaCy](https://spacy.io/usage/models), tokenization of Japanese and other languages is alpha supported.
Please support these languages if tokenization is useful than nothing for Fonduer.

**Comment by j-rausch** [comment]
We added support for Japanese spacy tokenization in #130. More languages that are alpha-supported by spacy could in principle be added in the future. See also our FAQ: https://fonduer.readthedocs.io/en/latest/user/faqs.html#how-can-i-use-use-fonduer-for-documents-in-languages-other-than-english

**Comment by HiromuHota** [comment]
Thank you so much for your hard work!
Now that even alpha-supported languages can theoretically be added in the future, this issue can be closed.
If someone wants another language to be supported (by Fonduer), he/she can create another issue for that specific language.
