### ISSUE TITLE
only parsing first page of 136 page pdf

### ISSUE THREAD

**Issue by clayms** [HazyResearch/fonduer#111]
When running the code in the fonduer-tutorials [max_storage_temp_tutorial](https://github.com/HazyResearch/fonduer-tutorials/blob/master/hardware/max_storage_temp_tutorial.ipynb) notebook to parse the pdf linked to below, only the first page is parsed.
I only get 19 sentences and all of them are from the first page.

**To Reproduce**
1. download https://www.theice.com/publicdocs/regulatory_filings/ICUS_Rules_Clean_up.pdf .
1. convert the pdf to html with poppler's pdftohtml.
1. rename html file to match pdf file.
1. run through code the same way as the fonduer-tutorials [max_storage_temp_tutorial](https://github.com/HazyResearch/fonduer-tutorials/blob/master/hardware/max_storage_temp_tutorial.ipynb) notebook.

**Expected behavior**
Get a list of all the sentences in the 136 page document. 

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04 running on Windows Subsystem for Linux
 - PostgreSQL Version: 10+192.pgdg16.04+1
 - Poppler Utils Version: 0.41.0-0ubuntu1.7
 - Fonduer Version: 0.2.3

**Comment by clayms** [comment]
related to this https://github.com/HazyResearch/pdftotree/issues/27#issuecomment-414673633 ?

**Comment by lukehsiao** [comment]
@clayms can you try converting the PDF to HTML using Adobe Acrobat to see if that is successful?

**Comment by clayms** [comment]
Using MS Word to convert leads to this error:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x95 in position 240614: invalid start byte
```

I replaced the MS Word generated html file with the Poppler pdftohtml file and ran the same code again, and it worked, but only output 19 sentences from the first page again.

**Comment by clayms** [comment]
possible alternative?

https://github.com/coolwanglu/pdf2htmlEX

**Comment by clayms** [comment]
this looks promising 

https://mupdf.com/docs/manual-mutool-draw.html

**Comment by clayms** [comment]
ok!  The following works

first:
```sh
mutool draw -o "ICUS_Rules_Clean_up.html" "ICUS_Rules_Clean_up.pdf"
```

then
```python
corpus_parser = Parser(structural=True, lingual=True, visual=True, pdf_path=pdf_path)
%time corpus_parser.apply(doc_preprocessor, parallelism=PARALLEL)
```
very slow for one document though
```
[INFO] fonduer.utils.udf - Clearing existing...
[INFO] fonduer.utils.udf - Running UDF...
CPU times: user 1.16 s, sys: 484 ms, total: 1.64 s
Wall time: 4min 44s
```

then
```python
from fonduer import Document, Sentence
print("Documents:", session.query(Document).count())
print("Sentences:", session.query(Sentence).count())
```
 
```
Documents: 1
Sentences: 6858
```

mutool is open source so it seems you should be recommending this as the conversion tool.
