### ISSUE TITLE
Wrong NER tag

### ISSUE THREAD

**Issue by HiromuHota** [HazyResearch/fonduer#125]
I'm not really sure, but it looks like a bug unless I'm missing something.

**Describe the bug**

`test_parser.py::test_parse_md_details` tests NER tags at [here](https://github.com/HazyResearch/fonduer/blob/master/tests/parser/test_parser.py#L137) like below:

```
assert header.ner_tags == ["ORG", "ORG"]
```
where `header.words == ['Sample', 'Markdown']`, but neither 'Sample' nor 'Markdown' is ORG (organization).

**To Reproduce**

You can confirm what is the right NET tag as follows:

```
import spacy
nlp = spacy.load('en')
doc = nlp(u'Apple is looking at buying U.K. startup for $1 billion')
print("Recognized number of NER: %d" % len(doc.ents))
"""This should print
Recognized number of NER: 3
"""

for ent in doc.ents:
    print(ent.text, ent.start_char, ent.end_char, ent.label_)

"""This should print  
Apple 0 5 ORG
U.K. 27 31 GPE
$1 billion 44 54 MONEY
"""

doc = nlp(u'Sample Markdown')
print("Recognized number of NER: %d" % len(doc.ents))
"""This should print
Recognized number of NER: 0
"""

for token in doc:
    print(token.text, token.pos_, token.dep_, token.ent_type_ if token.ent_type_ else "O")

"""This should print  
Sample NOUN compound O
Markdown PROPN ROOT O
"""
```

**Expected behavior**

The test should assert like this instead and should pass.
```
assert header.ner_tags == ["O", "O"]
```

**Environment (please complete the following information):**
- Fonduer Version: 0.3.0 (d5c1e9bb2acc62077f5360e1f9a658100d6e4cbe)
- spacy: 2.0.12

**Comment by j-rausch** [comment]
I am also confused about this behavior. I think it is caused by spacy itself.

We changed the parser to not process each sentence in isolation anymore.

This is an example of the same thing happening in the default spacy pipeline, when there's a second sentence in the document string:

```
doc = nlp(u'Sample Markdown')
first_sentence = list(doc.sents)[0]
for token in first_sentence:
    print(token.text, token.pos_, token.dep_, token.ent_type_ if token.ent_type_ else "O")
"""This prints
Sample NOUN compound ""
Markdown PROPN ROOT ""
"""


doc = nlp(u'Sample Markdown'
          u' This is some simple, basic markdown')
first_sentence = list(doc.sents)[0]
for token in first_sentence:
    print(token.text, token.pos_, token.dep_, token.ent_type_ if token.ent_type_ else "O")
"""This prints
Sample NOUN compound "ORG"
Markdown PROPN ROOT "ORG"
"""
```

**Comment by lukehsiao** [comment]
You can also inspect spaCy behavior [via this demo site](https://explosion.ai/demos/displacy-ent?text=Sample%20Markdown%0A&model=en_core_web_sm&ents=person%2Corg%2Cgpe%2Cloc%2Cproduct%2Cnorp%2Cdate%2Cper%2Cmisc). Seems to classify `Sample Markdown` as an ORG there as well (likely because of the capitalization?)

**Comment by HiromuHota** [comment]
I observed another interesting thing when adding a comma between first and second sentence.

```
doc = nlp(u'Sample Markdown',
          u' This is some simple, basic markdown')
first_sentence = list(doc.sents)[0]
for token in first_sentence:
    print(token.text, token.pos_, token.dep_, token.ent_type_ if token.ent_type_ else "O")
"""This prints
Sample NOUN compound O
Markdown PROPN ROOT O
"""

**Comment by j-rausch** [comment]
I think the second argument is interpreted as the 'disable' argument in that case.
Just debugged it and __call__ in spacy/language.py has the disable variable:
`disable = {str} ' This is some simple, basic markdown'`
In principle this should not work, because 'disable' should be of list type:
https://spacy.io/api/language#call

A bit off-topic:
Spacy doesn't seem to check for the type of this argument, so you could even accidentally disable pipeline components here:
```
        for name, proc in self.pipeline:
            if name in disable:
```
by feeding in:
```
input_list = [u'Sample Markdown', u' This is some simple, basic markdown']
doc = nlp(u'Sample Markdown', u' writing the word parser should disable that very component')
#first_sentence = list(doc.sents)[0]
for sent in doc.sents:
    for token in sent:
        print(token.text, token.pos_, token.dep_, token.ent_type_ if token.ent_type_ else "O")
"""
This will fail, because without a parser, sentences cannot be split
"""
```

**Comment by HiromuHota** [comment]
A few more tests at the spaCy's demo site (mentioned by @lukehsiao ) led me to a conclusion that this is not necessarily a bug of Fonduer and this "strange" behavior came from spaCy.
`Sample Markdown` could be classified as an organization and could be something else due to the surrounding words, capitalizations, etc.
So the test `test_parser.py::test_parse_md_details` is programmatically right, but not robust and semantically not quite right.
I'll try to make it right when I have time.
