### ISSUE TITLE
Context type discussions

### ISSUE THREAD

**Issue by mfboulos** [HazyResearch/fonduer#147]
Upon diving into the source code, and finding a situation where this would be imperative to improve the runtime of my program, I ran into 2 potential issues, or lack of knowledge of any workarounds.

I saw that Context types of candidate_subclass args are always set to Span in the database model. From my understanding, this can be any Context type (Sentence, Paragraph, etc.) but hasn't been implemented to do so. Is there another way to define this without manually editing the database?

On the same token, CandidateExtractor.apply() strictly generates TemporarySpans to represent candidates, which would disregard any changes to the Context type of any candidate_subclass arg. I also wonder if it's current possible to specify the Context that the CandidateExtractor considers to match the candidate model.

If I am wrong, please correct me, I am still attempting to understand the full workflow of this tool.

Edit: I realize that Ngrams.apply() is the ultimate cause of the TemporarySpan issue, but I also realize an implementation that I overlooked would accomplish what I am looking for. Also discovered that the context type changes throughout method calls, one requiring a Document type while the next requires Sentences. If it's in the works to customize the Context type of a candidate model, this may need to be looked at as well.

**Comment by SenWu** [comment]
> I saw that Context types of candidate_subclass args are always set to Span in the database model. From my understanding, this can be any Context type (Sentence, Paragraph, etc.) but hasn't been implemented to do so. Is there another way to define this without manually editing the database?

Right now, fonduer supports `Span` and `Image` as members of `candidate_subclass`, and the one you observed is because you define `candidate_subclass` with `Span`.

> On the same token, CandidateExtractor.apply() strictly generates TemporarySpans to represent candidates, which would disregard any changes to the Context type of any candidate_subclass arg. I also wonder if it's current possible to specify the Context that the CandidateExtractor considers to match the candidate model.

This is user-defined. If users want to have different types of `Context`s to extract, they need to update the `MentionSpace` to support that.

**Comment by mfboulos** [comment]
I have 2 questions then. Would it be feasible to expand the scope of possible contexts for candidate_subclass? And also, seeing how there's not much documentation for this project, where can I define a Context to extract? I have not come across MentionSpace in any of my exploring through the source code.

Note: for most cases where users are asking for clarity such as this, until there is a full set of documentation for how these things are possible, it might be necessary to give more insight on how these things are accomplished. I personally have very little Python experience, so exploring and understanding the source code can be exhausting and takes a lot of time out of the task that I'm using Fonduer for, but it's also my only option to build good foundational knowledge on its functionalities.

**Comment by lukehsiao** [comment]
> I have not come across MentionSpace in any of my exploring through the source code.

It is going to be renamed `MentionSpace` in v0.3.0. In v0.2.3 it is called `CandidateSpace`. 

To see some more of the functionalities, including defining a custom MentionSpace/CandidateSpace, i recommend checking out the [Tutorials](https://github.com/hazyresearch/fonduer-tutorials). Althought we do not have any tutorials in expanding the scope of possible contexts to extract, we do show custom MentionSpace/CandidateSpaces for the hardware application.

**Comment by SenWu** [comment]
Just to share you more information.

> Would it be feasible to expand the scope of possible contexts for candidate_subclass?

The answer is YES. The users can customize the `CandidateSpace` to the information they want to extract. As Luke mentioned, we have tutorials to show how to use it and there is a [hardware_imamge tutorial](https://github.com/HazyResearch/fonduer-tutorials/tree/master/hardware_image) to show how to extract images as candidates. In the v0.3.0, here are the pointer to how we build these [functionalities](https://github.com/HazyResearch/fonduer/tree/master/src/fonduer/candidates).

> And also, seeing how there's not much documentation for this project, where can I define a Context to extract?

We are pushing to have more documentation in the next release (v0.3.0).

Thanks for your comments/feedback!!!

**Comment by mfboulos** [comment]
Thanks! I understand how the CandidateSpace the user wants to extract is customizable, but only to the extent of Spans and Images. Do you foresee this expanding further, i.e. Sentences?

**Comment by SenWu** [comment]
Some of our collaborators' applications extract candidates based on the full sentence. So I would say, Yes. And it should be easy to extend to other objects well.

**Comment by kaikun213** [comment]
I am having a similar issue. In my case the spans can not just be in the cells of a table but also in the URL of an image or the document name. I wrote a quick and dirty custom Mentionspace and MentionRegex:

``` python
from fonduer.candidates.models.temporary_context import TemporaryContext
from fonduer.candidates import MentionNgrams, MentionDocuments, MentionFigures
from typing import Collection, Optional, Iterator

class StationMentionSpace(MentionNgrams):
    """Defines the **space** of Mentions.

    Defines the space of Mentions as all n-grams (n_min <= n <= n_max) in a
    Document *x*, divided into Sentences inside of html elements (such as table
    cells).

    :param n_min: Lower limit for the generated n_grams.
    :type n_min: int
    :param n_max: Upper limit for the generated n_grams.
    :type n_max: int
    :param split_tokens: Tokens, on which unigrams are split into two separate
        unigrams.
    :type split_tokens: tuple, list of str.
    :param types: If specified, only yield TemporaryFigureMentions whose url ends in
        one of the specified types. Example: types=["png", "jpg", "jpeg"].
    :type types: list, tuple of str
    """

    def __init__(
        self, n_min: int = 1, n_max: int = 5, split_tokens: Collection[str] = [], types: Optional[str] = None
    ) -> None:
        """Initialize MentionNgrams."""
        MentionNgrams.__init__(self, n_min=n_min, n_max=n_max, split_tokens=split_tokens)
        if types is not None:
            self.types = [t.strip().lower() for t in types]
        else:
            self.types = None

    def apply(self, doc: Document) -> Iterator[TemporaryContext]:
        """Generate MentionNgrams from a Document by parsing all of its Sentences.

        :param doc: The ``Document`` to parse.
        :type doc: ``Document``
        :raises TypeError: If the input doc is not of type ``Document``.
        """
        if not isinstance(doc, Document):
            raise TypeError(
                "Input Contexts to MentionNgrams.apply() must be of type Document"
            )

        for ts in MentionNgrams.apply(self, doc):
            yield ts
            
        for ts in MentionDocuments.apply(self, doc):
            yield ts
            
        for ts in MentionFigures.apply(self, doc):
            yield ts
```

``` python
from fonduer.candidates.models.document_mention import TemporaryDocumentMention
from fonduer.candidates.models.figure_mention import TemporaryFigureMention
from fonduer.candidates.models.span_mention import TemporarySpanMention
from fonduer.candidates.matchers import RegexMatchSpan

class RegexMatchFull(RegexMatchSpan):
    """Matches regex pattern on **full concatenated span, document-name and figure-urls**.

    :param rgx: The RegEx pattern to use.
    :type rgx: str
    :param ignore_case: Whether or not to ignore case in the RegEx. Default
        True.
    :type ignore_case: bool
    :param search: If True, *search* the regex pattern through the concatenated span.
        If False, try to *match* the regex patten only at its beginning. Default False.
    :type search: bool
    :param full_match: If True, wrap the provided rgx with ``(<rgx>)$``.
        Default True.
    :type full_match: bool
    :param longest_match_only: If True, only return the longest match. Default True.
        Will be overridden by the parent matcher like :class:`Union` when it is wrapped
        by :class:`Union`, :class:`Intersect`, or :class:`Inverse`.
    :type longest_match_only: bool
    """

    def _f(self, m: TemporaryContext) -> bool:
        """The internal (non-composed) version of filter function f"""
        
        def apply_rgx(attrib_span):
            # search for string as e.g. "_" split operator is used
            return (
                True
                if self.r.search(attrib_span)
                is not None
                else False
            )
        if isinstance(m, TemporarySpanMention):
            return RegexMatchSpan._f(self, m)
        if isinstance(m, TemporaryFigureMention):
            return apply_rgx(m.figure.url)
        if isinstance(m, TemporaryDocumentMention):
            return apply_rgx(m.document.name)
        
        raise ValueError(
            f"""
            {self.__class__.__name__} only supports 
            TemporarySpanMention, TemporaryFigureMention and TemporaryDocumentMention
            """
        )
```

It does extract the DocumentMentions and FigureMentions next to the SpanMentions.
However, I ran into two problems:

1) It will mention the whole document/figure and I can not refer only a span of the name/URL. Thus I would have to apply parser functions each time I use the candidate later e.g. to compare against the gold set or extract the final data.

2) Even though the mentions are extracted, somehow the candidate extractor does not build any candidates from the DocumentMentions and FigureMentions. My candidate extraction code is similar to the hardware-tutorial.

I will look more into it, but I would like to know if there is a simpler way to reference these spans? And what might fail the candidate extraction?
