### ISSUE TITLE
get_between_ngrams bug?

### ISSUE THREAD

**Issue by MhmdSaiid** [HazyResearch/fonduer#163]
Here is some code from the get_between_ngrams function.    
If span0 is before span1,then we should either take the right_ngrams of span0 or the left ngrams of span1.

If span 1 is before span0, we should take the right ngrams of span1 or the left ngrams of span0.

But in the code below, we take the left ngrams of span1.
Shouldn't it be the opposite?

https://github.com/HazyResearch/fonduer/blob/28c09d92b3e74b97db50ae2e1e94c6256cac1bd8/src/fonduer/utils/data_model_utils/textual.py#L31-L51

**Comment by lukehsiao** [comment]
Yes, you're right, we should take the left ngrams of span1. We'll fix this with the next release.
