### ISSUE TITLE
Visualizer fails with a PolicyError

### ISSUE THREAD

**Issue by lukehsiao** [HazyResearch/fonduer#170]
**Describe the bug**
This is a known bug caused by a recent change to ImageMagick and can be resolved by editing the policy file.

**To Reproduce**
In the [tutorials](https://github.com/HazyResearch/fonduer-tutorials/blob/b8ef73129bfa5b351d1fa5c3b6092e516f4b7c18/hardware/max_storage_temp_tutorial.ipynb), it will fail on this display call:

```py
from fonduer.utils.visualizer import Visualizer
from hardware_utils import entity_to_candidates
vis = Visualizer(pdf_path)

# Get a list of candidates that match the FN[10] entity
fp_cands = entity_to_candidates(FP[10], test_cands[0])
# Display a candidate
vis.display_candidates([fp_cands[0]])
```

**Error Logs/Screenshots**
The user will see an error like:
> PolicyError: not authorized `data/pdf/bc546-d.pdf' @ error/constitute.c/ReadImage/412
If applicable, add error logs or screenshots to help explain your problem.

When the Fonduer visualizer tries to display the PDF.

**Additional context**
The bug tracker for the issue on launchpad can be found here:

https://bugs.launchpad.net/ubuntu/+source/imagemagick/+bug/1796563

the change was introduced as a more secure default in the underlying package.

**Work-around**
A workaround for now is to simply change the policy in `/etc/ImageMagick-6/policy.xml` for PDFs to `read`.
```
<policy domain="coder" rights="read" pattern="PDF" />
```

**Comment by HiromuHota** [comment]
I also noticed this issue. The workaround that I took for Docker is to remove the file.
https://github.com/HazyResearch/fonduer-tutorials/blob/master/Dockerfile#L14
