### ISSUE TITLE
Is there a way to use Chinese with spaCy alpha support?

### ISSUE THREAD

**Issue by gzll** [HazyResearch/fonduer#177]
Want to use fonduer to parse Chinese document.

**Comment by SenWu** [comment]
Hi @gzll, please check our FAQs about how to use fonduer for documents in languages other than  English (https://fonduer.readthedocs.io/en/latest/user/faqs.html#how-can-i-use-use-fonduer-for-documents-in-languages-other-than-english).

**Comment by gzll** [comment]
I just followed the suggest in the FAQs " If you would like to use other languages with spaCy alpha support, which are not yet integrated in Fonduer, feel free to open an Issue."

**Comment by SenWu** [comment]
Hi @gzll, we love to support Chinese and if you can submit a PR of Chinese support that will help a lot.

**Comment by gzll** [comment]
OK. I will try.

**Comment by SenWu** [comment]
@gzll I have implemented a basic support for Chinese tokenization in fonduer here https://github.com/HazyResearch/fonduer/pull/192. Feel free to test it and enhance it.

**Comment by SenWu** [comment]
I am closing this issue now, feel free to reopen it if there is more need to do.

**Comment by gzll** [comment]
> @gzll I have implemented a basic support for Chinese tokenization in fonduer here #192. Feel free to test it and enhance it.

Great, Thanks
