### ISSUE TITLE
Supporting Fonduer on Windows

### ISSUE THREAD

**Issue by vishnuraj007** [HazyResearch/fonduer#180]
I am new to Fonduer , is there any steps to install fonduer in a windows machine.
https://fonduer.readthedocs.io/en/latest/user/getting_started.html
Above link shows to how to  install external dependence other than Windows system. 
Could you please help ?

**Comment by lukehsiao** [comment]
Fonduer does not currently support Windows. You could try using a Ubuntu virtual machine.

Or, you may be able to go through the process of debugging how to get it to work with Windows. If you're successful, we'd be happy to add it to our docs.
