### ISSUE TITLE
`get_row_ngrams` and `get_col_ngrams` return ngrams for mentions not inside tables

### ISSUE THREAD

**Issue by j-rausch** [HazyResearch/fonduer#186]
**Describe the bug**
`get_row_ngrams` and `get_col_ngrams` in https://github.com/HazyResearch/fonduer/blob/master/src/fonduer/utils/data_model_utils/tabular.py utilize `_get_axis_ngrams`.

If the given mention is not inside a table at all, the two functions could still return ngrams, because no `is_tabular()` check is performed before `get_sentence_ngrams` is called in https://github.com/HazyResearch/fonduer/blob/master/src/fonduer/utils/data_model_utils/tabular.py#L428.

 **Expected behavior**
I would expect `get_col_ngrams` and `get_row_ngrams` to return `None` or an empty list, if the mention is not inside a table (and not in a row/column as a consequence).

**Comment by SenWu** [comment]
@j-rausch Will you submit a PR to fix it? Thanks!

**Comment by j-rausch** [comment]
Sure, just wanted to make sure you guys agree on the desired behavior.
