### ISSUE TITLE
TypeError: apply() missing 1 required positional argument: 'doc' during mention_extractor.apply(docs) that extracts MentionCells

### ISSUE THREAD

**Issue by HiromuHota** [HazyResearch/fonduer#188]
**Describe the bug**

`MentionCells` cannot be extracted and the following error message appears.
[error.txt](https://github.com/HazyResearch/fonduer/files/2646709/error.txt)

**To Reproduce**

1. `docker-compose up` hiromuhota/fonduer-tutorials:0.4.0
2. Open hardware_image/transistor_image_tutorial.ipynb
3. Replace figs with cells like below

```
# Fig = mention_subclass("Fig")
# fig_matcher = LambdaFunctionFigureMatcher(func=do_nothing_matcher)
# figs = MentionFigures(types=['png'])
# mention_extractor = MentionExtractor(session, [Fig], [figs], [fig_matcher], parallelism=PARALLEL)

Field = mention_subclass("Field")
field_matcher = DoNothingMatcher
fields = MentionCells
mention_extractor = MentionExtractor(session, [Field], [fields], [field_matcher], parallelism=PARALLEL)
```
4. Execute `mention_extractor.apply(docs)`

**Expected behavior**

`MentionCells` is extracted without error.

**Error Logs/Screenshots**
Attached.

**Environment (please complete the following information):**
 - OS: docker
 - PostgreSQL Version: 11.1-1.pgdg90+1
 - Poppler Utils Version: N/A
 - Fonduer Version: 0.4.0

**Additional context**

**Comment by HiromuHota** [comment]
See the actual notebook if it helps.
[transistor_image_tutorial.ipynb.zip](https://github.com/HazyResearch/fonduer/files/2646759/transistor_image_tutorial.ipynb.zip)

**Comment by SenWu** [comment]
In the code above, you need to use `DoNothingMatcher()` in `MentionExtractor ` instead?

**Comment by HiromuHota** [comment]
That was it.
Both `DoNothingMatcher()` and `MentionCells()` should be with parentheses, meaning they should be instantiated.
