### ISSUE TITLE
Update code to use Python 3.6+'s f-strings

### ISSUE THREAD

**Issue by lukehsiao** [HazyResearch/fonduer#190]
Given that we're only supporting Python 3.6+, we can take advantage of Python 3.6's f-strings in the codebase. 

Clearly, this has no functional impact, just might be a simple way to cleanup or make some logging code more concise. Low priority.

**Additional context**
- https://realpython.com/python-f-strings/
- https://www.python.org/dev/peps/pep-0498/

**Comment by SenWu** [comment]
#202
