### ISSUE TITLE
Allow disabling specific feature types through config file

### ISSUE THREAD

**Issue by lukehsiao** [HazyResearch/fonduer#219]
**Is your feature request related to a problem? Please describe.**

Fonduer includes a feature library of textual, structural, tabular, and visual features. It would be convenient for experimental purposes to be able to disable classes of features through the [configuration file](https://fonduer.readthedocs.io/en/latest/user/config.html).

**Additional context**
For example, it would make running feature ablation studies extremely straightforward if the feature libraries used could be configured in the file.

**Comment by SenWu** [comment]
This PR #283 gave the API to support this.
