### ISSUE TITLE
Travis CI job takes longer than the 50 minutes limit

### ISSUE THREAD

**Issue by HiromuHota** [HazyResearch/fonduer#229]
**Describe the bug**

Travis CI job takes longer than the 50 minutes limit.
(https://docs.travis-ci.com/user/customizing-the-build/#build-timeouts)
As a result, recent jobs for PRs, which have to start without pip cache, did not finish.

**To Reproduce**
1. Submit a PR.

**Expected behavior**

Travis CI job should finish even for PRs.

**Error Logs/Screenshots**
If applicable, add error logs or screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/20668349/54854608-b835cf00-4cb0-11e9-9c22-959bc0667dc9.png)

**Environment (please complete the following information):**
N/A

**Additional context**

**Comment by lukehsiao** [comment]
This will ideally be resolved along with #230.

**Comment by SenWu** [comment]
Resolved in #230
