### ISSUE TITLE
Why does Fonduer require PostgreSQL version 9.6 or above?

### ISSUE THREAD

**Issue by HiromuHota** [HazyResearch/fonduer#242]
The [Doc](https://fonduer.readthedocs.io/en/latest/user/getting_started.html#installing-external-dependencies) says "Fonduer requires PostgreSQL version 9.6 or above."
Why 9.6 or above?

**Comment by SenWu** [comment]
Fonduer used to use database operations using sql commend instead of SQLAlchemy query which requires advanced syntax that only provides in PostgreSQL v9.6 or later. Fonduer is only tested to work using PostgreSQL 9.6 or above. So, we recommend to use PostgreSQL v9.6 or later.

**Comment by HiromuHota** [comment]
Now that SQLAlchemy is used, Fonduer may work without any problem (maybe performance?) with postgres 9.5 or earlier, but not tested. I see. 

> advanced syntax that was only supported in PostgreSQL v9.6 or later

Just for the record, which one specifically? The [ReleaseNote](https://www.postgresql.org/about/news/1703/) of 9.6 says a list of new features introduced at 9.6.

**Comment by SenWu** [comment]
Yes, It probably works with old version as well. We were using SQL directly to improve the performance  (e.g., https://github.com/HazyResearch/fonduer/pull/157/commits/e7ab1a10f965aee842845d2f763047ae417c6556).

**Comment by HiromuHota** [comment]
I didn't mean which line of code, but I meant which feature, introduced at 9.6, Fonduer is used to depend on.

**Comment by SenWu** [comment]
The syntax we were using in the SQL is only supported in 9.6 or later. While we don't use it anymore, it's not an issue now.

**Comment by HiromuHota** [comment]
Thanks for clarification!
