### ISSUE TITLE
Serializable Fonduer model

### ISSUE THREAD

**Issue by HiromuHota** [HazyResearch/fonduer#259]
**Is your feature request related to a problem? Please describe.**

I develop a Fonduer-based app locally on my laptop.
Once it's done, I'd like to package [the whole Fonduer pipeline](https://fonduer.readthedocs.io/en/latest/user/getting_started.html#the-fonduer-pipeline) (parsing, extraction, featurization, and classification) and deploy it to a remote place to serve.
However, a Fonduer-based app is not easy to package hence not easy to deploy.

**Describe the solution you'd like**

Add a Fonduer model class that is 
1. Serializable (e.g., a class with `save` and `load` member methods like below)

```
class FonduerModel:
    def save(path_to_save):
    def load(path_to_load):
```

2. Capable of executing any phase of the Fonduer pipeline
3. (Hopefully) Manageable by MLflow

**Describe alternatives you've considered**

I can create one or more of python scripts that do all the phase, package them, and deploy it.
This is cumbersome because the python script has to include many things (matchers, mention_classes, mention_spaces, candidate_classes, etc.) and it is not obvious what should be included for serving.

**Additional context**

I'd like to make Fonduer more deployable and servable.
I've been testing MLflow to package a Fonduer-based app and found it was difficult to do so when there is no serializable Fonduer model.

**Comment by SenWu** [comment]
This is a great idea! Really excited to see/chat about how we can approach it to make Fonduer much easier to use.

**Comment by HiromuHota** [comment]
I did some research how to serialize a dynamically created class (e.g., mention/candidate subclasses in Fonduer) and I found that cloudpickle or dill can serialize such a class.
However, the thing becomes more complicated when you try to serialize `LambdaFunctionMatcher`-based matchers. Those user-defined lambda functions have to be serialized along with matchers, which could be cumbersome.
Serializability is nice but packagiability (of user-created python files for mention/candidate subclasses, matchers, spaces, etc.) would be good enough.

**Comment by trungtv** [comment]
Hello, 
I am also interested in serving Fonduer models in concurrent environments. If there is an effort for that, I would like to join in.
Thanks for your great work.

**Comment by HiromuHota** [comment]
I've created a custom MLflow model to package a (trained) Fonduer model.
In addition to packaging, this custom model can be used to serve the packaged model.

Currently this custom MLflow model includes some hard-coded part, hence needs cleanup; but I'd love to contribute it to the community if it is useful for other people.
@SenWu @trungtv, let us know your thoughts.

**Comment by SenWu** [comment]
@HiromuHota Awesome! We definitely love to have it since more and more people want to use it! Happy to chat and contribute as well! We should have a tutorial for that as well. 👍

**Comment by trungtv** [comment]
@HiromuHota great! I am happy to contribute on this milestone for Fonduer.

**Comment by HiromuHota** [comment]
I think fonduer-mlflow became in good shape and ready for to be submitted as a PR against fonduer.
Let me create a PR and submit it.
