### ISSUE TITLE
Clarification on Document, Paragraph, Section, and Sentence

### ISSUE THREAD

**Issue by HiromuHota** [HazyResearch/fonduer#262]
This is not a bug.
I'd want a clarification on Document, Paragraph, Section, and Sentence.
It is clear that which element in HTML becomes which data models like Figure, Table, Caption. E.g., `<img>` and `<figure>` become Figure.
However, it is not obvious which element in HTML becomes Document, Paragraph, Section, and Sentence.

**Comment by SenWu** [comment]
Right now, we use predefined tag to define those elements as follow:

*Document:* each file is one document
*Section:* `["html", "section"]` tag
*Figure:* `["img", "figure"]` tag
*Table:* `"table"` tag
*Paragraph:* every chunk of context in the node, such as content in `["text", "tail"]`
*Sentence:* the parse results from NLP parser (e.g., Spacy) define the sentence.

One idea to improve it is to use a configuration file to define those indicator tags for different applications.

Thanks for your question!
Sen

**Comment by HiromuHota** [comment]
Thanks for your clarification.
https://lxml.de/tutorial.html#elements-contain-text helps me better understand the <i>Paragraph</i>.
In the following example, 
```<html><body>Hello. Nice to meet you.<br/>Snorkel is great. Fonduer is even greater.</body></html>```
"Hello. Nice to meet you." is one paragraph, and "Snorkel is great. Fonduer is even greater." is another.

_Sentence_ is beyond what HTML elements tell you.
"Hello." is one sentence, "Nice to meet you." is another. But this depends on the NLP parser.

Let me add these information to the documents.
