### ISSUE TITLE
How to extract multiple relationships?

### ISSUE THREAD

**Issue by yzj19870824** [HazyResearch/fonduer#273]
It works well when I extract binary relationships , such as （Target, Location) , (Target, Action) and (Target, Time). But how can I get multiple relationships from those binary relationships, for example (Target, Action, Location, Time) 

Thanks in advance

**Comment by yzj19870824** [comment]
It's improper to concatenate 3 binary relationship directly . Because there maybe the same target name in a sentence .

**Comment by SenWu** [comment]
Thanks for your interests in our research!

There are several options to do multi-nary relation.

One option is to define the multi-nary relation directly, e.g., `TargetActionLocationTime = candidate_subclass("TargetActionLocationTime", [Target, Action, Location, Time])`. One thing you might need to take care is how to extract features for that.

Another way is to do binary relation first and combine them afterward. As you mentioned, there can be more than one the same mention in the sentence, but each one has its own `stable_id` which is unique. You should be able to `stable_id` to combine them. Check here for [example](https://github.com/HazyResearch/fonduer/blob/77063e4b2291cbe798cf7b27af2daf37d02693e2/src/fonduer/candidates/models/span_mention.py#L46).

Sen

**Comment by yzj19870824** [comment]
Thank you , I'll give it a shot
