### ISSUE TITLE
from fonduer.learning.utils import confusion_matrix ImportError: cannot import name 'confusion_matrix'

### ISSUE THREAD

**Issue by yangliu0** [HazyResearch/fonduer#275]
----> 5 from fonduer.learning.utils import confusion_matrix
      6 from fonduer.supervision.models import GoldLabel, GoldLabelKey
      7 

ImportError: cannot import name 'confusion_matrix'

I use fonduer 0.6.2,but when I import this module, I encounter this problem

**Comment by lukehsiao** [comment]
See https://github.com/HazyResearch/fonduer-tutorials/issues/60
