### ISSUE TITLE
Issues about Parser

### ISSUE THREAD

**Issue by TorRient** [HazyResearch/fonduer#284]
When fonduer uses pdftotext, it has an error in the list top, list bottom, list right, list left, list page because the repeated words lead to wrong list top, list bottom, list right, list left, list page coordinates.

**Comment by SenWu** [comment]
Hi @TorRient ,

Thanks for your question! Unfortunately, Fonduer doesn't officially support pdftotext right now. And we always welcome PRs to improve to Fonduer in anyways.

Sen
