### ISSUE TITLE
Type hints

### ISSUE THREAD

**Issue by HiromuHota** [HazyResearch/fonduer#290]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I have to look at the source codes to check the type of arguments/return.

**Describe the solution you'd like**

1. Type hints (PEP484) are written to source codes like

```python
def greeting(name: str) -> str:
    return 'Hello ' + name
```

2. (Eventually) enforce type checking during pre-commit

For example by [flake8-mypy](https://pypi.org/project/flake8-mypy/)

**Describe alternatives you've considered**

Depending on the editor (PyCharm, etc.), type/rtype documentation like below gives you type hinting.
However, I'm not sure this is equivalent to the type hints (PEP484).

```
def greeting(name):
    """
    greeting

    :param name: description
    :type name: type description
    :return: description
    :rtype: type description
    """
    return 'Hello ' + name
```

**Additional context**

**Comment by SenWu** [comment]
This is definitely a good idea!!! Let's do this!

**Comment by SenWu** [comment]
Any suggestions?

**Comment by HiromuHota** [comment]
[PyAnnotate](https://github.com/dropbox/pyannotate) looks good. This is a tool that auto-generates PEP-484 annotations.
This has been developed by the same team, at Dropbox, who has originally developed mypy.
Let me try PyAnnotate for a while.

By the way, I don't know exactly what you mean by the following, but I don't think we need a folder 'type' for type hinting. Let me know if I'm mistaken.
> One more question about typing: do you think it's a good idea to have type folder to include all types in Fonduer?

**Comment by HiromuHota** [comment]
https://github.com/Instagram/MonkeyType could be another option.

**Comment by HiromuHota** [comment]
So basically, both MonkeyType and PyAnnotate do the same thing: 1. collect types at runtime and 2. insert collected types to the source code.
I ran `pytest tests` with each but none of the two traced the calls of Fonduer methods because `pytest tests` ran against the Fonduer package installed in site-packages, which is ignored by MonkeyType and PyAnnotate by default.
Fortunately, MonkeyType takes care of such a case by specifying the package to be traced in an environment variable (see [here](https://monkeytype.readthedocs.io/en/latest/faq.html#i-run-tests-against-my-package-installed-in-site-packages-and-i-get-no-traces)).

The following works with Fonduer,

1. Collect types
```bash
$ pip install pytest-monkeytype
$ export MONKEYTYPE_TRACE_MODULES=fonduer
$ cd fonduer # move to the root directory
$ py.test --monkeytype-output=./monkeytype.sqlite3
```

2. Insert collected types
```bash
$ cd src
$ mv ../monkeytype.sqlite3 ./
$ # Get a listing of modules annotated by monkeytype
$ monkeytype list-modules
$ # Insert the collected types to a module (e.g., fonduer.parser.parser)
$ monkeytype apply fonduer.parser.parser
```

*You may not want to set `CI=TRUE` as it produces a huge file of `monkeytype.sqlite3` (like more than 3GB).

**Comment by SenWu** [comment]
Great! I think this is definitely a great tool. If I understand it correctly, we can use this tool to auto insert the type and manually correct the wrong ones and add dynamic typing checking using travis test. Does this sound correct?

**Comment by HiromuHota** [comment]
Yes, you understood it correctly.
It doesn't make any mistake but the coverage is not necessarily perfect depending on the code that runs during the type collection.
The following is one snippet example:
```
     def apply(
-        self, doc_loader, pdf_path=None, clear=True, parallelism=None, progress_bar=True
-    ):
+        self, doc_loader: HTMLDocPreprocessor, pdf_path: None = None, clear: bool = True, parallelism: Optional[int] = None, progress_bar: bool = True
+    ) -> None:
```

`doc_loader` should be typed `DocPreprocessor` instead of `HTMLDocPreprocessor`.
`HTMLDocPreprocessor` has been chosen because the (test) code only uses it.
So yes, we have to manually correct the wrong ones but the tool would do a great job.

**Comment by SenWu** [comment]
Super! Let's do it. This will make Fonduer much easier to use.
