### ISSUE TITLE
HTML candidate visualizer

### ISSUE THREAD

**Issue by lauratolosi** [HazyResearch/fonduer#314]
Evaluating Fonduer results is sometimes difficult, in absence of expert annotations. Visually displaying the candidates that are predicted as true is of great help, one can go through the document and quickly judge correct or mistaken instances.

The `visualizer` module is meant to assist with that, but I have encountered many problems with ImageMagick, mostly errors of type `CorruptImageError: unable to read image data` on `Image.resize()` .  This error occurs on some pages of my PDF documents, not all, but I can't detect a pattern or a cause. In general, I don't think that trying to visualize PDFs is the best strategy.

I would like to ask whether an HTML visualizer is available, that highlights the span of each mention in the candidate. And if not available, why? Is there a good reason to prefer to transform PDFs into Images and then add candidates?

**Comment by SenWu** [comment]
Hi @lauratolosi, thanks for question!
Unfortunately, we don't have HTML visualizer right now. But I do think it's great to have one.

For your last question, Fonduer uses a unified data model to do knowledge base construction and the transform you mentioned is to build that data model.

Sen

**Comment by lauratolosi** [comment]
Hi, thanks!

I wrote a viewer myself. It was very hard because the data model does not calculate the absolute offset of a sentence in the html file, even though there seems to be an attribute for that : `https://fonduer.readthedocs.io/en/latest/user/parser.html#fonduer.parser.models.Sentence.abs_char_offsets` . But they seem to be `0` always. I checked the code and their values are not updated.

So my code is very hack-y, I will share it after I comment it properly, in case somebody else is interested.

**Comment by HiromuHota** [comment]
@lauratolosi It'd be great if you could report another issue for the always-0-abs_char_offsets.

**Comment by lauratolosi** [comment]
I think this issue could be closed, because with the absolute character offsets fixed (abs_char_offsets), one can easily add such html tags: `background-color:yellow` before the mention.
Thank you for looking into this!

**Comment by HiromuHota** [comment]
@lauratolosi I'd suggest to use the `xpath` attribute, which is currently available only for Sentence, to locate the corresponding html element in the original html file.
