### ISSUE TITLE
Zombie process occurs when I apply multimodal featurization or label functions

### ISSUE THREAD

**Issue by yzj19870824** [HazyResearch/fonduer#315]
**Describe the bug**
Zombie process occurs when I apply multimodal featurization or label functions(I set the parallelism=20, which is less than the number of CPU core of my server). 
When I use command "ps -ef|grep python" , I can find that the last process shows "python [defunct]" .
And when I use command "top -Hp [fonduer-main-process-id]" , only two threads  are listed, both states are "S" (which means SLEEP), no CPU or MEMORY resource obtained.
BUT no error information is printed .
The direct reflection is the lowest speed I ever see, almost 1200 candidates spend 2 hours !!!
Can anyone help me? My project maybe canceled by this DISASTER.

 - OS: CentOS 7.4
 - PostgreSQL Version:  9.6
 - Fonduer Version:  0.5.0

**Comment by HiromuHota** [comment]
I'd suggest to try the latest release of Fonduer (v0.7.0) and Ubuntu (18.04).
Fonduer is not well tested with CentOS.

Also set parallelism much lower.
20 parallel would choke the backend postgres server.

**Comment by HiromuHota** [comment]
I think #324 and #335 has resolved this issue, or at least mitigated it.

**Comment by SenWu** [comment]
Close for now. Feel free to reopen if it's still an issue.
