### ISSUE TITLE
Inner HTML elements are processed after the tail text

### ISSUE THREAD

**Issue by HiromuHota** [HazyResearch/fonduer#333]
**Describe the bug**

In tests/data/html_simple/md.html, `<em>italics and later <strong>bold</strong></em>. Even` is processed in the following order:

1. `italics and later `
2. `. Even`
3. `bold`

This is illustrated in #12 too.

**To Reproduce**
1. Run `tests/parser/test_parser.py::test_parse_md_details` and set a breakpoint

**Expected behavior**

The said sentence is processed in the following order:

1. `italics and later `
2. `bold`
3. `. Even`

**Environment (please complete the following information):**
 - Fonduer Version: [0.7.0 and master(3d5392ccfb092e23ac861bc06815c56374d63b55)]

**Additional context**

Why this happens?

When the `node` is `<em>italics and later <strong>bold</strong></em>`, node.text (=`italics and later `) and node.tail (=`. Even`) are processed, the next node `<strong>bold</strong>` is processed.

**Comment by SenWu** [comment]
So, the expected order should be (1) node.text, (2) text in the inner node, and (node.tail)?

**Comment by HiromuHota** [comment]
I think so.
This is especially true when you want to align words between HTML and PDF (related to #12).
I don't think this is a major issue, though.
