### ISSUE TITLE
Can someone share the advertisement dataset used for Experiment in the paper

### ISSUE THREAD

**Issue by AshutoshUpadhya** [HazyResearch/fonduer#370]
Can someone please share the advvertisment dataset mentioned in the paper. I am exploring  fonduer for one usecase and would like to go through that dataset.

Thanks in advance

**Comment by SenWu** [comment]
Hi @AshutoshUpadhya,

Thanks for your interests in our research!
Unfortunately, the Advertisements dataset is not public available. But I would suggest you to take a look at our [wiki tutorial](https://github.com/HazyResearch/fonduer-tutorials/tree/master/wiki) which has similar data format (HTML) and problems as we discussed in Advertisements dataset.

Hope this can help you!
Sen
