### ISSUE TITLE
.docx word document parsing giving error

### ISSUE THREAD

**Issue by AshutoshUpadhya** [HazyResearch/fonduer#375]
Firstly, I am new to fonduer and was trying to parse a word document using wiki president tutorial. I changed the parser to Doc_preprocessor  but it gave error "not implemented" . Probably because  the document object has nothing though I have placed the document at mentioned path. Do I need to provide HTML  for word docs as well?

code:

from fonduer.parser.preprocessors import DocPreprocessor
from fonduer.parser import Parser

docs_path = "data/contracts/"
doc_preprocessor = DocPreprocessor(docs_path)
doc_preprocessor

corpus_parser = Parser(session, structural=True, lingual=True)
%time corpus_parser.apply(doc_preprocessor)#, parallelism=PARALLEL)

Error:
NotImplementedError                       Traceback (most recent call last)
<timed eval> in <module>()

/softwares/anaconda3/lib/python3.6/site-packages/fonduer/parser/parser.py in apply(self, doc_loader, clear, parallelism, progress_bar, pdf_path)
    140             clear=clear,
    141             parallelism=parallelism,
--> 142             progress_bar=progress_bar,
    143         )
    144 

/softwares/anaconda3/lib/python3.6/site-packages/fonduer/utils/udf.py in apply(self, doc_loader, clear, parallelism, progress_bar, **kwargs)
     63 
     64         # Track the last documents parsed by apply
---> 65         self.last_docs = set(doc.name for doc in doc_loader)
     66 
     67         # Execute the UDF

/softwares/anaconda3/lib/python3.6/site-packages/fonduer/utils/udf.py in <genexpr>(.0)
     63 
     64         # Track the last documents parsed by apply
---> 65         self.last_docs = set(doc.name for doc in doc_loader)
     66 
     67         # Execute the UDF

/softwares/anaconda3/lib/python3.6/site-packages/fonduer/parser/preprocessors/doc_preprocessor.py in _generate(self)
     33         doc_count = 0
     34         for fp in self.all_files:
---> 35             for doc in self._get_docs_for_path(fp):
     36                 yield doc
     37                 doc_count += 1

/softwares/anaconda3/lib/python3.6/site-packages/fonduer/parser/preprocessors/doc_preprocessor.py in _get_docs_for_path(self, fp)
     51         file_name = os.path.basename(fp)
     52         if self._can_read(file_name):
---> 53             for doc in self._parse_file(fp, file_name):
     54                 yield doc
     55 

/softwares/anaconda3/lib/python3.6/site-packages/fonduer/parser/preprocessors/doc_preprocessor.py in _parse_file(self, fp, file_name)
     58 
     59     def _parse_file(self, fp: str, file_name: str) -> Iterator[Document]:
---> 60         raise NotImplementedError()
     61 
     62     def _can_read(self, fpath: str) -> bool:

NotImplementedError:

Can someone please tell where I am missing?

**Comment by HiromuHota** [comment]
Currently, .docx word document is not supported. "Doc" in the name of `DocPreprocessor` has nothing to do with MS word doc files. "Doc" just means documents in general.
Fonduer only supports csv, tsv, text, html files as of today.

Technically speaking, `DocPreprocessor` is not meant to be used directly. It should be inherited and its methods should be implemented by the child class. For example, `HTMLDocPreprocessor` is such a child class for HTML files.

Therefore, you have to convert your MS doc files into one of those supported formats and use the corresponding child class of `DocPreprocessor`.

Hope this helps.

**Comment by AshutoshUpadhya** [comment]
Thanks  @HiromuHota for your quick response.
so what text documents mean here, I have text documents, I mean word documents and notepad files. I tried .txt file with textDocPreprocessor  but its giving 'module' not found error. Can you pls explain. 
This will help in getting where exactly I can use fonduer.

**Comment by AshutoshUpadhya** [comment]
Anyone any update pls?

**Comment by lukehsiao** [comment]
We have no plans to support DOCX.

For using text, try the [TextDocPreprocessor](https://fonduer.readthedocs.io/en/latest/user/parser.html#preprocessors). In general, please make sure to include an error log and follow the issue template for us to have enough information to help you. 

If you have further issues, please open a new ticket about that issues specifically. Closing this issue for DOCX now.
