### ISSUE TITLE
Enforce match between DB and candidate encodings

### ISSUE THREAD

**Issue by jdunnmon** [HazyResearch/fonduer#38]
Suggest putting a check in the baseline fonduer docpreprocessor method that checks to ensure that the database encoding is the same as the candidate text encodings, else you'll end up with DB errors when running the featurizers.

**Comment by Pardhu448** [comment]
Got an error when running tutorial notebooks at Multimodal featurization step. Is it related to #38 ?
Thanks.
---------------------------------------------------------------------------
Copying formation_measurement_feature to postgres
CalledProcessError                        Traceback (most recent call last)
<timed exec> in <module>()

~/Documents/Projects/local_governments/text_mining/fonduer_env/lib/python3.5/site-packages/fonduer/async_annotations.py in apply(self, split, key_group, replace_key_set, update_keys, update_values, storage, ignore_keys, **kwargs)
    327                     % table_name)
    328             copy_postgres(segment_file_blob, table_name,
--> 329                           'candidate_id, keys, values')
    330             remove_files(segment_file_blob)
    331 

~/Documents/Projects/local_governments/text_mining/fonduer_env/lib/python3.5/site-packages/fonduer/async_annotations.py in copy_postgres(segment_file_blob, table_name, tsv_columns)
    173                                                       table_name,
    174                                                       tsv_columns)
--> 175     _out = subprocess.check_output(cmd, stderr=subprocess.STDOUT, shell=True)
    176     print(_out)
    177 

/usr/lib/python3.5/subprocess.py in check_output(timeout, *popenargs, **kwargs)
    624 
    625     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
--> 626                **kwargs).stdout
    627 
    628 

/usr/lib/python3.5/subprocess.py in run(input, timeout, check, *popenargs, **kwargs)
    706         if check and retcode:
    707             raise CalledProcessError(retcode, process.args,
--> 708                                      output=stdout, stderr=stderr)
    709     return CompletedProcess(process.args, retcode, stdout, stderr)
    710 

CalledProcessError: Command 'cat /tmp/formation_measurement_formation_measurement_feature_0_*.tsv | PGPASSWORD=uvce psql formation_measurement -U postgres -p 5432 -c "COPY formation_measurement_feature(candidate_id, keys, values) FROM STDIN" --set=ON_ERROR_STOP=true' returned non-zero exit status 2>

**Comment by lukehsiao** [comment]
> Got an error when running tutorial notebooks at Multimodal featurization step. Is it related to #38 ?

I don't think this is related to encoding. I would guess that it is an issue in your postgres connection string. Is connecting with user `postgres`, password `uvce` and port `5432` correct? Per [the psql docs](https://www.postgresql.org/docs/current/static/app-psql.html)

> psql returns 0 to the shell if it finished normally, 1 if a fatal error of its own occurs (e.g. out of memory, file not found), 2 if the connection to the server went bad and the session was not interactive, and 3 if an error occurred in a script and the variable ON_ERROR_STOP was set.

**Comment by SenWu** [comment]
In v0.3.0, fonduer will allow the user to set database encoding.
