### ISSUE TITLE
Raise an error/warning when labeler.get_gold_labels returns a label matrix with all values being -1 (abstain)

### ISSUE THREAD

**Issue by HiromuHota** [HazyResearch/fonduer#403]
**Is your feature request related to a problem? Please describe.**

When you try to get a label matrix of gold labels like below, but you forget to load gold labels beforehand,

```
L_gold_train = labeler.get_gold_labels(train_cands, annotator='gold')
```

You will get a label matrix with all values being -1 (abstain).

```
print(L_gold_train[0].reshape(-1))
[-1. -1. -1. ... -1. -1. -1.]
```

Without knowing that it is wrong, you will be receiving 0 Emp. Acc. like below.

```
LFAnalysis(L=L_train[0], lfs=sorted_lfs).lf_summary(Y=L_gold_train[0].reshape(-1))
```

![image](https://user-images.githubusercontent.com/20668349/79777833-b0e65800-82ec-11ea-8fbb-20a5729f252b.png)

**Describe the solution you'd like**

Raise an error when the label matrix returned by `labeler.get_gold_labels` contains -1 at any one or more of cells.

**Describe alternatives you've considered**

Alternatively, `labeler.get_gold_labels` can give a warning message.

**Additional context**

I got this situation when I was updating the hardware tutorial.

**Comment by lukehsiao** [comment]
@HiromuHota When I try this locally before loading gold labels, I don't get all `-1`, I just get an empty ndarray:

```
print(temp[0].reshape(-1))
[]
```

Am I missing something?

**Comment by HiromuHota** [comment]
When I got this situation, I loaded gold labels only for test data.
If you try to get gold labels for training data, you'd get a label matrix of all -1.
