### ISSUE TITLE
get_neighbor_cell_ngrams with "absolute" parameter

### ISSUE THREAD

**Issue by kaikun213** [HazyResearch/fonduer#413]
**Is your feature request related to a problem? Please describe.**
It is hard to access a heading of a sub-table in a HTML where all sub-tables are in one `<table>` tag via a labeling function. `get_col_ngrams` can return the correct ngrams but without directions or distance. `get_neighbor_cell_ngrams` can return the direction, but does not consider columns which span multiple such as a heading to be neighboring.

**Describe the solution you'd like**
I checked the code and adding an `absolute` flag to the `get_neighbor_cell_ngrams` function which is then passed to the function calls for row/col difference
```
row_diff = min_row_diff(sentence, root_cell, absolute=absolute)
col_diff = min_col_diff(sentence, root_cell, absolute=absolute)
```
could solve that problem. Instead of the `False` boolean default as it is currently.

**Describe alternatives you've considered**
Alternatively, I am quite often in need to access the table information of an ngram (e.g. which row/col is the sentence). The functions could provide an option to return the sentences instead of the ngrams. As far as I know I have not seen a way to get from the ngram back to the sentence(?).

**Additional context**
The example HTML in case needed for reproduction: 
[1_DJ Index 4-1 Peak.zip](https://github.com/HazyResearch/fonduer/files/4610678/1_DJ.Index.4-1.Peak.zip)

Example with an image: Access the heading "MID COLUMBIA" from the cell with the value `$235.33`. This is needed to know in which table the value is, as all this "sub-tables" are in one HTML table.
![Screenshot from 2020-05-11 17-57-24](https://user-images.githubusercontent.com/18282228/81582932-ec86b600-93b0-11ea-85bb-231edfcf5234.png)

**Comment by SenWu** [comment]
This looks like a very useful feature.
Can you make a PR for this so other users can benefit from this functionality?

Thanks for pointing out this issue.
-Sen

**Comment by kaikun213** [comment]
In order to not break the existing logic for directions, I decided against the `absolute` argument and instead fixed it in the min_range_diff.
