### ISSUE TITLE
The content for "MLflow model for Fonduer" is missing from Read The Docs

### ISSUE THREAD

**Issue by HiromuHota** [HazyResearch/fonduer#464]
## Description of the bug

The content for "MLflow model for Fonduer" is missing from Read The Docs
![image](https://user-images.githubusercontent.com/20668349/85349449-4ea80000-b4b3-11ea-941d-86faa684e21d.png)

## To Reproduce
1. Visit https://fonduer.readthedocs.io/en/latest/user/packaging.html#mlflow-model-for-fonduer

## Expected behavior

The content for "MLflow model for Fonduer" should appear on Read The Docs.

![image](https://user-images.githubusercontent.com/20668349/85349393-39cb6c80-b4b3-11ea-9a15-a2cacc984cbb.png)

## Error Logs/Screenshots
If applicable, add error logs or screenshots to help explain your problem.

## Environment (please complete the following information)
 - OS: [e.g. Ubuntu 18.04]
 - PostgreSQL Version: [e.g. 9.6]
 - Poppler Utils Version: [e.g. 0.62.0]
 - Fonduer Version: [e.g. 0.6.0]

**Comment by lukehsiao** [comment]
For reference, ReadTheDocs isn't reporting any build error, but it looks like there actually is errors. The full log is attached:

[rtd-log.txt](https://github.com/HazyResearch/fonduer/files/4820855/rtd-log.txt)

When building the docs, RTD doesn't actually pip install the fonduer package, so any packages that are required to build the docs should be included in docs/requirements.txt, which is installed before building the docs. In this case, it looks like the docs require `cloudpickle`. Alternatively (and usually preferred), we can mock the imports we don't need. This is done in docs/conf.py, like we do for scipy, snorkel, tqdm, etc.

**Comment by HiromuHota** [comment]
Thanks for looking into this.
I could add `cloudpickle` into docs/conf.py, but do you know how to test it? Like can we emulate the RTD's build environment?

**Comment by lukehsiao** [comment]
One way to test would be to make a clean virtualenv, `pip install docs/requirements.txt`, and then try `make docs`. I believe that mimics the environment. If we need more, we can make a separate branch, and actually build it on RTD to see.

**Comment by HiromuHota** [comment]
Thanks. Let me try to build and check it.

**Comment by HiromuHota** [comment]
I confirmed that the issue has been resolved at https://fonduer.readthedocs.io/en/latest/user/packaging.html.
