### ISSUE TITLE
parser.apply does not return for a long time even though the progress bar indicates it finishes parsing

### ISSUE THREAD

**Issue by HiromuHota** [HazyResearch/fonduer#494]
## Description of the bug

This is not a bug, but a performance issue.
This is not noticeable when parsing a small number of documents, but parser.apply does not return even though the progress bar indicates it finishes parsing a long time ago (1 hour or more ago).

## To Reproduce
1. Parse many documents (my case: ~2500)

## Expected behavior

`parser.apply` returns when the progress bar indicates it finished parsing all the documents.

## Error Logs/Screenshots
If applicable, add error logs or screenshots to help explain your problem.

## Environment (please complete the following information)
 - OS: Debian Buster
 - PostgreSQL Version: 12.1
 - Poppler Utils Version: N/A
 - Fonduer Version: 0.8.3+dev (01e0d9319b523aff7aa7f5c583a9f330b0705ecc)

**Comment by HiromuHota** [comment]
I found it stuck at `self.session.commit()` in `UDFRunner._apply`.

https://github.com/HazyResearch/fonduer/blob/01e0d9319b523aff7aa7f5c583a9f330b0705ecc/src/fonduer/utils/udf.py#L168

**Comment by HiromuHota** [comment]
I think this is a regression from 807a4b8a5960ef8cd11df892f98bee60ecf9a804 (#490).
By this commit, all the changes during `parser.apply` are held in memory until they are flushed out to the database, which could easily overflow the RAM size when many documents are processed.

**Comment by HiromuHota** [comment]
> I think the idea of processing the rows in chunks is to limit the
memory usage of the Python process. Until you call session.flush(),
all your modifications are held in memory. For small numbers of rows
this isn't a problem, but for huge numbers, it might be.

https://groups.google.com/g/sqlalchemy/c/hK4vIziMWOQ/m/98O5d2dqCgAJ

**Comment by robbieculkin** [comment]
Hi, I'm seeing this bug in the max_storage_temp_tutorial.
![Screen Shot 2021-01-25 at 3 29 39 PM](https://user-images.githubusercontent.com/20375994/105778943-3a812100-5f22-11eb-9a8e-3d56579919c6.png)

**Comment by robbieculkin** [comment]
I'm still seeing this issue. It looks like all processes' data are held in memory, then written to the DB using a single process. I'm debugging via `top`, where I see 
1. memory usage is split across parallel processes
2. next, all memory stacks up in a single process
3. lastly, my machine kills the process due to OOM error

I can workaround this via a for loop wrapper but this doesn't seem like the optimal way to use `.apply`. 

It seems @HiromuHota may have moved on to other projects; @SenWu, do you have time to look at this issue?

**Comment by lukehsiao** [comment]
Your description sounds correct to me, and this is definitely a real bottleneck several have run into. We would love to try and resolve this, but I suspect it wouldn't be a quick fix. 

I'm going to reopen this issue.

**Comment by YasushiMiyata** [comment]
I proposed a pull request related to this issue (#494) by #541.
OOM error seems to happen in the case that sqlalchemy keeps large document data on memory untill `commit` from `add`.
The proposal (#541) is doing `commit` immediately after `add` to free memory.
https://github.com/HazyResearch/fonduer/blob/5ab8e9c7bad34ad86800b7b077aa8342f590ec27/src/fonduer/parser/parser.py#L135

**Comment by YasushiMiyata** [comment]
In addition, I got test results; python memory usage (max about 3GB -> 500MB) and processing time (339 sec -> 268 sec).
This test is parsing all html files from [tests/download_data.sh](https://github.com/HazyResearch/fonduer/blob/5ab8e9c7bad34ad86800b7b077aa8342f590ec27/tests/download_data.sh) and saving them to postgres.

**Comment by robbieculkin** [comment]
Thanks for your work on this. This will be a major reliability improvement for my use case and will eliminate several workarounds.

**Comment by YasushiMiyata** [comment]
I renew PR #544 from #541 because #541 fails rebase by my wrong merge order.

**Comment by lukehsiao** [comment]
The proposed PR has been merged. @robbieculkin, if you happen to have time to test the current `master` branch to verify that this is working for you, that would be great.

**Comment by robbieculkin** [comment]
I've tested `master` on ~200 docs and can confirm that these changes fix OOM errors and slow performance. Many thanks for the fix.
