### ISSUE TITLE
BBox value errors

### ISSUE THREAD

**Issue by saikalyan9981** [HazyResearch/fonduer#507]
While getting bbox values, say left values for some sentences, the left value for "\n" in the sentence is being an outlier. which is causing the bbox of entire sentence as wrong. [which is calculated as min of all lefts in sentence]

For Example if sentence is 
[Hello
World] 
with words as [Hello,"\n", World]
the left values are like [ 213,154,213].
This is observed when Hello\nWorld sentence is in middle of a page of a pdf like this:
page elements:
| abc    ` ` ` ` ` ` ` ` ` `      Hello   ` ` ` ` ` ` ` ` ` `        efg |
| def    ` ` ` ` ` ` ` ` ` `       world    ` ` ` ` ` ` ` ` ` `      hij  |

please, let me know if i need to add any other details.

**Comment by saikalyan9981** [comment]
Thanks @HiromuHota , I think that's the root cause for this issue. Any idea, if hOCR will be included in next version?

**Comment by HiromuHota** [comment]
The current visual linker links words between HTML and PDF by just looking at similarities of each word.
As a result, common words, which appear many times in a document, tend to be mis-linked.

I'm currently working on hOCR. As this would require an architectural change, it would need to increase a minor version like (v0.9.X).
Please stay tuned.
