### ISSUE TITLE
Can Fonduer extract arbitrary tabular data?

### ISSUE THREAD

**Issue by munaAchyuta** [HazyResearch/fonduer#51]
I have a requirement where a table has three columns. first column data represent reach row's main header. and second,third column respective value of each row (in second,third column small regular expression function required to filter digits..etc). and data are text . 

i want fonduer to consider each row as one candidate. how can i do that ?
and some cases where one row might have multiple paragraphs(sub-rows), in that case i want fonduer to give me each paragraph in that row as separate row with concatenating main header(paragraph) to each sub-row. 
can fonduer do this type of task ?

when i was trying to understand fonduer flow, i found it keeping data in terms of phrases in "Phrase" table with keeping all track. but to solve my/above issue how can this going to helpful ?

Thanks in Advance.

**Comment by lukehsiao** [comment]
>I have a requirement where a table has three columns. first column data represent reach row's main header. and second,third column respective value of each row (in second,third column small regular expression function required to filter digits..etc). and data are text .
>
>i want fonduer to consider each row as one candidate. how can i do that ?
and some cases where one row might have multiple paragraphs(sub-rows), in that case i want fonduer to give me each paragraph in that row as separate row with concatenating main header(paragraph) to each sub-row.
> can fonduer do this type of task ?

Some more concrete examples of what you're trying to do would be helpful here. However, from your description, I do not think Fonduer is the right tool for you. Fonduer allows you to extract specific relations from richly formatted data. It does not allow you to transform arbitrary tables in richly formatted data into a structured format like PostgreSQL. 

>when i was trying to understand fonduer flow, i found it keeping data in terms of phrases in "Phrase" table with keeping all track. but to solve my/above issue how can this going to helpful ?

Please check out our [blog post](https://hazyresearch.github.io/snorkel/blog/fonduer.html) and/or [paper](https://arxiv.org/abs/1703.05028) to see more details about Fonduer's pipeline and the tasks that it solves. You can also check the [fonduer tutorials](https://github.com/HazyResearch/fonduer-tutorials) for a walk-through. You can learn more about the data model in Section 3.1 of the paper.
