### ISSUE TITLE
Parser can't handle big tables?

### ISSUE THREAD

**Issue by Lin-Leon-MENG** [HazyResearch/fonduer#532]
## Description of the bug
I was trying to apply `Fonduer` on a few `html` files converted from `xlsx` sheets. During the parsing phase, while most of them worked fine, one of the files can't be successfully parsed, in a way that no error message was printed, but the resulting database was empty.

One noticeable difference of this specific file is its size. The original sheet is a 700+ by 50+ table, the converted html file is 16MB, which are significant bigger than the others. After exploring for a while, I might suspect the parser doesn't handle large tables very well. By any chance do you have any experience on this type of issue? Thank you!

P.S. As part of the inspection, I tripled the data volume (simple repetition of the rows for three time) of a smaller file to make the size comparable with the file of issue. Nothing was returned again, however, the parsing on the smaller file itself is good.

## To Reproduce
Since the data is confidential, I can't upload here. But I may be able to create some fake data if needed.

## Expected behavior
The `apply` method of `parser` failed when the original worksheet is bigger(?), without prompting error messages.

## Error Logs/Screenshots
![image](https://user-images.githubusercontent.com/49058444/103314768-c7df5d00-49d8-11eb-83ee-8393a6d35de0.png)

## Environment (please complete the following information)
 - PostgreSQL Version: 13.1
 - Fonduer Version: 0.8.2

**Comment by SenWu** [comment]
Hi @Lin-Leon-MENG, can you share the fake data and the code you were using so we can reproduce your issue?

Thanks,
Sen

**Comment by Lin-Leon-MENG** [comment]
Hi @SenWu thanks for getting back to me.

[fake_data.zip](https://github.com/HazyResearch/fonduer/files/5773418/fake_data.zip)

I created this fake data for your reference. There're 4 files included.
- fake.xlsx: original data of interest
- fake.html: converted using a Python module `xlsx2html`
- fake_double.html: copy-paste the whole table (content within `<tr>...</tr>` tag) so it's twice bigger.
- fake_triple.html: likewise, table is 3 times bigger

**Codes**

I used Jupyter Notebook to run these codes and tried a few times. Again, the `parser` worked on fake.html, but not on the other two (the progress bar showed completion for the fake_double file though).

I've been playing around with Fonduer for a while and not had this kind of issue before. It'd awesome if you could take a look, in case I'm doing something wrong. Much appreciated!

```
! createdb -h postgres fake
```

```
%load_ext autoreload
%autoreload 2
%matplotlib inline
import os
import sys
import logging

# Configure logging for Fonduer
logging.basicConfig(stream=sys.stdout, format='[%(levelname)s] %(name)s - %(message)s')
log = logging.getLogger('fonduer')
log.setLevel(logging.INFO)

PARALLEL = 1 
ATTRIBUTE = "fake"
conn_string = 'postgresql://postgres:5432/' + ATTRIBUTE


from fonduer import Meta
session = Meta.init(conn_string).Session()
```

```
from fonduer.parser.preprocessors import HTMLDocPreprocessor
from fonduer.parser import Parser

docs_path = 'html/'
max_docs = 100
preprocessor = HTMLDocPreprocessor(docs_path, max_docs=max_docs)

parser = Parser(
        session,
        parallelism=1,
        structural=True,
        blacklist=["style", "script", "title"],
        language="en",
        lingual=True,
        strip=True,
        replacements=[
            ("[\u2010\u2011\u2012\u2013\u2014\u2212]", "-"),  # hyphen-alike to a hyphen
            ("\n", " "),  # a line break to a space
            ("&nbsp;", "N/A"),
        ],
        tabular=True,
    )
parser.clear()

parser.apply(preprocessor, parallelism=PARALLEL, clear=False)
```

**Comment by Lin-Leon-MENG** [comment]
Hi @SenWu, I just solved the issue thanks to the input from @YasushiMiyata.

Turns out it's because of my docker container memory ran out. I didn't realize memory could be a problem. 

I'm sorry for the inconvenience and taking up your time.
