### ISSUE TITLE
Refactor docstrings and enforce using flake8-docstrings

### ISSUE THREAD

**Issue by lukehsiao** [HazyResearch/fonduer#66]
Some of our docstrings may be inaccurate, and many are missing altogether.

**Comment by lukehsiao** [comment]
```
53    D100 Missing docstring in public module
21    D101 Missing docstring in public class
95    D102 Missing docstring in public method
44    D103 Missing docstring in public function
13    D104 Missing docstring in public package
57    D105 Missing docstring in magic method
40    D107 Missing docstring in __init__
28    D200 One-line docstring should fit on one line with quotes
3     D202 No blank lines allowed after function docstring
97    D205 1 blank line required between summary line and description
6     D208 Docstring is over-indented
1     D209 Multi-line docstring closing quotes should be on a separate line
171   D400 First line should end with a period
48    D401 First line should be in imperative mood
677
```
We have quite a ways to go here.

**Comment by lukehsiao** [comment]
For v0.3.0, we just need docstrings for our API. We will not enforce it with flake8-docstrings yet.

**Comment by HiromuHota** [comment]
Can you reopen this as ultimately I'd like Fonduer to be enforced by flake8-docstrings?
How about enforcing just for APIs for now? (I don't know how to narrow the check scope, though).

If we can't narrow the check scope to APIs, we can check docstrings for everything and ignore violations at this moment.
Preferably, the number of violations would better be monitored like Coveralls does for test coverage to motivate us to write docstrings.
