### ISSUE TITLE
Error when copying feature updates to Postgresql database

### ISSUE THREAD

**Issue by MhmdSaiid** [HazyResearch/fonduer#73]
Hello,
I am getting this error when applying the batch feature annotator:
**CalledProcessError: Command 'cat /tmp/reg_topic_reg_topic_feature_0_*.tsv |  psql reg_topic  -p 5432 -c "COPY reg_topic_feature_updates(candidate_id, keys, values) FROM STDIN" --set=ON_ERROR_STOP=true' returned non-zero exit status 1**.

These are the info that I got:

[INFO] fonduer.udf - Clearing existing...
[INFO] fonduer.udf - Running UDF...
[INFO] fonduer.async_annotations - Copying reg_topic_feature_updates to postgres

Thank you in advance.

**Comment by lukehsiao** [comment]
Hi @MhmdSaiid, which version of Fonduer are you using? Do you have a username or password for your PostgreSQL database?

**Comment by MhmdSaiid** [comment]
Hi @lukehsiao,
I am using Fonduer 0.1.8.
I am using Ubuntu 16.04.
My PostgreSQL database has a username but no password.
I am actually connected to a VM that is hosting the jupyter notebook server.

**Comment by SenWu** [comment]
Hi @MhmdSaiid, thanks for your information. Can you share us the full log of your run? Also, can you try the cmd in your terminal?
`cat /tmp/reg_topic_reg_topic_feature_0_*.tsv | psql reg_topic -p 5432 -c "COPY reg_topic_feature_updates(candidate_id, keys, values) FROM STDIN" --set=ON_ERROR_STOP=true`

**Comment by MhmdSaiid** [comment]
Hello @SenWu,
I re-encountered the error again. Unfortunately, deleting the tables didn't work this time.
Here is the log I get when running the **BatchFeatureAnnotator** :

ERROR START:
******************************************************************************************************
[INFO] fonduer.udf - Clearing existing...
[INFO] fonduer.udf - Running UDF...
[INFO] fonduer.async_annotations - Copying reg_topic_feature_updates to postgres
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<timed exec> in <module>()

~/.venv/lib/python3.5/site-packages/fonduer/async_annotations.py in apply(self, split, key_group, replace_key_set, update_keys, update_values, storage, ignore_keys, **kwargs)
    320                     % table_name)
    321             copy_postgres(segment_file_blob, table_name,
--> 322                           'candidate_id, keys, values')
    323             remove_files(segment_file_blob)
    324 

~/.venv/lib/python3.5/site-packages/fonduer/async_annotations.py in copy_postgres(segment_file_blob, table_name, tsv_columns)
    171                                                       username, port,
    172                                                       table_name, tsv_columns)
--> 173     _out = subprocess.check_output(cmd, stderr=subprocess.STDOUT, shell=True)
    174     logger.info(_out)
    175 

/usr/lib/python3.5/subprocess.py in check_output(timeout, *popenargs, **kwargs)
    624 
    625     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
--> 626                **kwargs).stdout
    627 
    628 

/usr/lib/python3.5/subprocess.py in run(input, timeout, check, *popenargs, **kwargs)
    706         if check and retcode:
    707             raise CalledProcessError(retcode, process.args,
--> 708                                      output=stdout, stderr=stderr)
    709     return CompletedProcess(process.args, retcode, stdout, stderr)
    710 

CalledProcessError: Command 'cat /tmp/reg_topic_reg_topic_feature_0_*.tsv |  psql reg_topic  -p 5432 -c "COPY reg_topic_feature_updates(candidate_id, keys, values) FROM STDIN" --set=ON_ERROR_STOP=true' returned non-zero exit status 1_
******************************************************************************************************
ERROR FINISH

Also executing the command in the terminal gave me this:

perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_TIME = "en_GB.UTF-8",
	LC_MONETARY = "en_GB.UTF-8",
	LC_ADDRESS = "en_GB.UTF-8",
	LC_TELEPHONE = "en_GB.UTF-8",
	LC_NAME = "en_GB.UTF-8",
	LC_MEASUREMENT = "en_GB.UTF-8",
	LC_IDENTIFICATION = "en_GB.UTF-8",
	LC_NUMERIC = "en_GB.UTF-8",
	LC_PAPER = "en_GB.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
ERROR:  malformed array literal: "{CORE_e1_LENGTH_2,CORE_e1_SPAN_TYPE_[EXPLICIT],CORE_e1_STARTS_WITH_CAPITAL,CORE_e2_SPAN_TYPE_[EXPLICIT],CORE_e2_LENGTH_1,DDL_e1_W_LEMMA_L_2_R_3_[error  "
DETAIL:  Unexpected end of input.
CONTEXT:  COPY reg_topic_feature, line 1, column keys: "{CORE_e1_LENGTH_2,CORE_e1_SPAN_TYPE_[EXPLICIT],CORE_e1_STARTS_WITH_CAPITAL,CORE_e2_SPAN_TYPE_[EXPLIC..."

Thank you for your time.

Best Regards,
Mohammed Saeed

**Comment by lukehsiao** [comment]
Hi @MhmdSaiid, can you attach the `/tmp/reg_topic_reg_topic_feature_0_*.tsv` file?

**Comment by MhmdSaiid** [comment]
Hello @lukehsiao,
I was trying several stuff and found out that the problem was with how I converted from PDF to HTML.
Using Adobe Acrobat fixed the problem.
Unfortunately, I wasn't able to get the same error again so that I can attach the requested file.
Sorry for that and for the late reply.

Best Regards,
Mohammed Saeed

**Comment by lukehsiao** [comment]
Hi @MhmdSaiid, `pdftotree` doesn't convert to plain HTML, but rather, it
converts to a html-like tree representation. It's on the roadmap to have
`pdftotree` integrated into Fonduer so that prior conversion from PDF to HTML
is not required, but currently `pdftotree` output is not supported.

Closing this feature issue since it appears using Acrobat resolved the problem.
