### ISSUE TITLE
Typo in `get_page_horz_percentile` function

### ISSUE THREAD

**Issue by chyikwei** [HazyResearch/fonduer#79]
Hi, 

I am testing `lf_helpers` functions and find the return type of `get_page_horz_percentile` is a tuple instead of float value.
```Python
return bbox_from_span(span).left, page_width
```
I think the `,` should be `/`, right?

Source:
https://github.com/HazyResearch/fonduer/blob/master/fonduer/supervision/lf_helpers.py#L920

**Comment by SenWu** [comment]
Hi @chyikwei,

Thanks for pointing this out. This typo will be fixed in #80.

**Comment by chyikwei** [comment]
thanks! close this issue now.
