### ISSUE TITLE
Upgrade to spaCy 2.x

### ISSUE THREAD

**Issue by lukehsiao** [HazyResearch/fonduer#9]
For reference:

https://github.com/HazyResearch/snorkel/issues/830

**Comment by dhimmel** [comment]
Is https://github.com/HazyResearch/fonduer/commit/f310221c14319811c313887fa169f20a4f6b0cc1 something that should be cherry picked into HazyResearch/snorkel? CC @stephenbach

**Comment by stephenbach** [comment]
Turns out we got a lot of this functionality from here: https://github.com/HazyResearch/snorkel/pull/876

Copied over the more robust package checking here: https://github.com/HazyResearch/snorkel/commit/ff1785e35c749f6674b15fc9b2cec96b4fc0718c
