### ISSUE TITLE
Transistor Image Tutorial - UnicodeEncodeError from CorpusParser

### ISSUE THREAD

**Issue by Allen8838** [HazyResearch/fonduer#90]
Hello,

First off, thanks for this interesting library. I have only gone through it a little bit but am quite excited to explore its full capabilities.  

I am going through the transistor_image_tutorial at the moment. Running the lines:

```
corpus_parser = Parser(structural=True, lingual=True, visual=True, pdf_path=pdf_path, flatten=[])
%time corpus_parser.apply(doc_preprocessor, parallelism=PARALLEL)
```
I get the following UnicodeEncodeError. 

![transistor_image_tutorial - unicodeencodeerror](https://user-images.githubusercontent.com/35154803/43555578-05f25406-95c9-11e8-886d-d9b4a7dc049c.PNG)

As a result, when I execute the next line, I get 

Documents: 0
Sentences: 0
Figures: 0

I was wondering if there is a workaround for this or if I needed to do something first to avoid the error and get the same result as the original transistor_image_tutorial file. Thank you.

**Comment by lukehsiao** [comment]
Hi @Allen8838, are you using OSX or Linux?  Also, is this the [latest tutorials](https://github.com/HazyResearch/fonduer-tutorials) using Fonduer 0.2.3?

**Comment by Allen8838** [comment]
Hi @lukehsiao, I am using Bash on Ubuntu on Windows. Yes, this is the latest tutorial using Fonduer 0.2.3.

**Comment by lukehsiao** [comment]
I'm not able to reproduce this on my Ubuntu machine. Can you post the full error log?

**Comment by Allen8838** [comment]
Please see below. It's one error log, broken into several snips. 

![image](https://user-images.githubusercontent.com/35154803/43559087-797bdf62-95da-11e8-8bd1-da5e0815eee6.png)

![image](https://user-images.githubusercontent.com/35154803/43559246-50d023c4-95db-11e8-95cd-acd99fa4f925.png)

![image](https://user-images.githubusercontent.com/35154803/43559271-6717547c-95db-11e8-829f-8a8f55240ffe.png)

![image](https://user-images.githubusercontent.com/35154803/43559283-7974203c-95db-11e8-9428-ddaf26083480.png)

![image](https://user-images.githubusercontent.com/35154803/43559301-91bfb8a4-95db-11e8-90e2-81d072617f18.png)

![image](https://user-images.githubusercontent.com/35154803/43559314-a053a8f8-95db-11e8-9149-68d961e5590d.png)

![image](https://user-images.githubusercontent.com/35154803/43559324-adc14ae0-95db-11e8-890c-0d84331bde7c.png)

![image](https://user-images.githubusercontent.com/35154803/43559345-bbf2df48-95db-11e8-90d5-2a895c487bc5.png)

**Comment by lukehsiao** [comment]
Which version of PostgreSQL are you using?

Can you verify that your postgres encoding is set to UTF8? Check by runnning:

```
$ psql stg_temp_max_figure -c "SHOW SERVER_ENCODING"
```

**Comment by Allen8838** [comment]
Thanks for your help. I am using version 9.5.13.

Yea, you're right about the problem. The postgres encoding is set to SQL_ASCII. 

![image](https://user-images.githubusercontent.com/35154803/43589881-a4ecaf56-963d-11e8-9e7f-2bc71eb8c9f3.png)

I tried the line above in creating a database but still saw that the encoding was SQL_ASCII. In case it may be helpful for others, I ended using this line instead. 

! createdb -E UTF8 -T template0 stg_temp_max_figure

Which got the Parser to work. 

Would you offhand know how I can change the default encoding to UTF8? I did some digging and saw that I can make the change through initdb but was unable to find this file. 

Thanks again.

**Comment by lukehsiao** [comment]
Thanks for the follow-up @Allen8838! I don't know offhand how to change default encoding, but I do suspect it's based on setting the templates to be UTF8 rather than ASCII. 

Also note that Fonduer expects Postgres 9.6 or above, so there may be other issues you run into with using postgres 9.5.13, so I'd recommend upgrading if you can.

**Comment by Allen8838** [comment]
Thank you.
